name: Golang lint, vet and unit test pipeline

on: [push, pull_request]

jobs:
  test:
    name: github (govet, golint and gotest)
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Checkout project code
        uses: actions/checkout@v3
      - name: Checkout openstack-k8s-operators-ci project
        uses: actions/checkout@v3
        with:
          repository: openstack-k8s-operators/openstack-k8s-operators-ci
          path: ./openstack-k8s-operators-ci
      - name: Run govet.sh
        run: ./openstack-k8s-operators-ci/test-runner/govet.sh
      - name: Run golint.sh
        run: ./openstack-k8s-operators-ci/test-runner/golint.sh
      - name: Run gotest.sh
        run: ./openstack-k8s-operators-ci/test-runner/gotest.sh

  golangci:
    name: github (golangci)
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Checkout project code
        uses: actions/checkout@v3
      - name: Run golangci lint
        uses: golangci/golangci-lint-action@v2
        with:
          version: latest
          args: --timeout 5m

  minikube:
    runs-on: ubuntu-latest
    steps:
      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.18.x
      - name: Checkout project code
        uses: actions/checkout@v3
      - name: Setup minikube
        run: |
          minikube start --memory=max --cpus=max --vm-driver=docker
          minikube -p minikube docker-env | grep "export" | sed 's/export //' | sed 's/"//g' >> $GITHUB_ENV
      - name: Deploy CRD
        run: |
          make manifests generate fmt vet deploy IMG="quay.io/jlarriba/ansibleee-operator:latest"
          sed -i "s/openstack/ansibleee-operator-system/g" examples/ansibleee-playbook-local.yaml
          kubectl config set-context --current --namespace=ansibleee-operator-system
          kubectl apply -f examples/ansibleee-playbook-local.yaml
          sleep 10
          kubectl get events --sort-by='.metadata.creationTimestamp'
          kubectl logs -l app.kubernetes.io/component=operator -c manager --tail=10000
